group=de.playerdatasync
version=26.5.5-SNAPSHOT

# Performance Optimizations
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

# Reposilite Credentials (fill in your local values)
# DO NOT COMMIT YOUR REAL PASSWORD TO GIT
reposilite_username=your_reposlite_user
reposilite_password=your_reposlite_passwort
