modLoader="javafml"
loaderVersion="[54,)"
license="MIT"

[[mods]]
modId="playerdatasync"
version="${mod_version}"
displayName="PlayerDataSync"
authors="CraftingStudioPro"
description='''
Cross-platform player data synchronization (Forge 1.21.4).
'''

[[dependencies.playerdatasync]]
    modId="forge"
    mandatory=true
    versionRange="[54,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.playerdatasync]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.4,1.22)"
    ordering="NONE"
    side="BOTH"
